OpenAI client tests. Training code.

diff --git a/scripts/cray b/scripts/cray
--- a/scripts/cray
+++ b/scripts/cray
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-# This script was generated by bashly 1.2.2 (https://bashly.dannyb.co)
+# This script was generated by bashly 1.2.6 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
 # :wrapper.bash3_bouncer
@@ -51,7 +51,7 @@ cray_build_image_usage() {
   printf "cray build-image - Build image from dockerfile\n\n"
 
   printf "%s\n" "Usage:"
-  printf "  cray build-image\n"
+  printf "  cray build-image TARGET\n"
   printf "  cray build-image --help | -h\n"
   echo
 
@@ -62,6 +62,15 @@ cray_build_image_usage() {
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "TARGET"
+    printf "\n"
+    printf "    %s\n" "Allowed: cpu, nvidia"
     echo
 
   fi
@@ -246,10 +255,25 @@ cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
 # :command.command_functions
 # :command.function
 cray_build_image_command() {
+
   # cmd/build_image_command.sh
   inspect_args
 
-  docker build -t cray:latest --shm-size=8g .
+  target=${args[target]}
+
+  declare -a vllm_target_device
+  declare -a docker_platform
+
+  # If target is cpu, build the image with the cpu base image
+  if [ "$target" == "cpu" ]; then
+      vllm_target_device=("cpu")
+      docker_platform=("linux/arm64/v8")
+  else
+      vllm_target_device=("cuda")
+      docker_platform=("linux/amd64")
+  fi
+
+  docker build --platform ${docker_platform} --build-arg BASE_NAME=${target} --build-arg VLLM_TARGET_DEVICE=${vllm_target_device} -t cray:latest --shm-size=8g .
 
   echo $(green_bold Successfully built image)
 
@@ -257,6 +281,7 @@ cray_build_image_command() {
 
 # :command.function
 cray_up_command() {
+
   # cmd/up_command.sh
   #inspect_args
 
@@ -266,6 +291,7 @@ cray_up_command() {
 
 # :command.function
 cray_test_command() {
+
   # cmd/test_command.sh
   inspect_args
 
@@ -336,7 +362,8 @@ cray_test_command() {
 parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
+    key="$1"
+    case "$key" in
       --version | -v)
         version_command
         exit
@@ -422,7 +449,8 @@ parse_requirements() {
 cray_build_image_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
+    key="$1"
+    case "$key" in
       --help | -h)
         long_usage=yes
         cray_build_image_usage
@@ -452,13 +480,32 @@ cray_build_image_parse_requirements() {
       *)
         # :command.parse_requirements_case
         # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
+        # :argument.case
+        if [[ -z ${args['target']+x} ]]; then
+          args['target']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
 
         ;;
 
     esac
   done
+
+  # :command.required_args_filter
+  if [[ -z ${args['target']+x} ]]; then
+    printf "missing required argument: TARGET\nusage: cray build-image TARGET\n" >&2
+
+    exit 1
+  fi
+
+  # :command.whitelist_filter
+  if [[ -n ${args['target']:-} ]] && [[ ! ${args['target']:-} =~ ^(cpu|nvidia)$ ]]; then
+    printf "%s\n" "target must be one of: cpu, nvidia" >&2
+    exit 1
+  fi
 
 }
 
@@ -466,7 +513,8 @@ cray_build_image_parse_requirements() {
 cray_up_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
+    key="$1"
+    case "$key" in
       --help | -h)
         long_usage=yes
         cray_up_usage
@@ -510,7 +558,8 @@ cray_up_parse_requirements() {
 cray_test_parse_requirements() {
   # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
+    key="$1"
+    case "$key" in
       --help | -h)
         long_usage=yes
         cray_test_usage
@@ -619,11 +668,11 @@ initialize() {
 
 # :command.run
 run() {
-  declare -A args=()
-  declare -A deps=()
-  declare -a other_args=()
-  declare -a env_var_names=()
-  declare -a input=()
+  declare -g -A args=()
+  declare -g -A deps=()
+  declare -g -a other_args=()
+  declare -g -a env_var_names=()
+  declare -g -a input=()
   normalize_input "$@"
   parse_requirements "${input[@]}"
 
